variable "name" {
  description = "(Optional) Name of the Auto Scaling Group. By default generated by Terraform. Conflicts with name_prefix."
  default = null
}

variable "tag" {
  description = "(Optional) Configuration block(s) containing resource tags. See Tag below for more details."
  default = null
}

variable "tags" {
  default = null
}

variable "capacity_rebalance" {
  description = "(Optional) Whether capacity rebalance is enabled. Otherwise, capacity rebalance is disabled."
  default = null
}

variable "launch_configuration" {
  description = "(Optional) Name of the launch configuration to use."
  default = null
}

variable "placement_group" {
  description = "(Optional) Name of the placement group into which you'll launch your instances, if any."
  default = null
}

variable "desired_capacity" {
  description = "(Optional) Number of Amazon EC2 instances that should be running in the group. (See also Waiting for Capacity below.)"
  default = 1
}

variable "min_size" {
  description = "(Required) Minimum size of the Auto Scaling Group. (See also Waiting for Capacity below.)"
  default = 1
}

variable "max_size" {
  description = "(Required) Maximum size of the Auto Scaling Group."
  default = 1
}

variable "force_delete" {
  description = " (Optional) Allows deleting the autoscaling group without waiting for all instances in the pool to terminate. You can force an autoscaling group to delete even if it's in the process of scaling a resource. Normally, Terraform drains all the instances before deleting the group. This bypasses that behavior and potentially leaves resources dangling."
  default = true
}

variable "load_balancers" {
  description = "(Optional) A list of elastic load balancer names to add to the autoscaling group names. Only valid for classic load balancers. For ALBs, use target_group_arns instead."
  default = null
}

variable "health_check_type" {
  description = "(Optional) EC2 or ELB. Controls how health checking is done."
  default = null
}

variable "health_check_grace_period" {
  description = "(Optional) Default: 300 seconds - after instance comes into service before checking health."
  default = null
}

variable "termination_policies" {
  description = "(Optional) A list of policies to decide how the instances in the auto scale group should be terminated. The allowed values are OldestInstance, NewestInstance, OldestLaunchConfiguration, ClosestToNextInstanceHour, OldestLaunchTemplate, AllocationStrategy, Default."
  default = ["OldestInstance", "OldestLaunchConfiguration"]
}

variable "target_group_arns" {
  description = "(Optional) A list of aws_alb_target_group ARNs, for use with Application or Network Load Balancing."
  default = null
}

variable "suspended_processes" {
  description = "(Optional) A list of processes to suspend for the AutoScaling Group. The allowed values are Launch, Terminate, HealthCheck, ReplaceUnhealthy, AZRebalance, AlarmNotification, ScheduledActions, AddToLoadBalancer. Note that if you suspend either the Launch or Terminate process types, it can prevent your autoscaling group from functioning properly."
  default = null
}

variable "default_cooldown" {
  description = "(Optional) Amount of time, in seconds, after a scaling activity completes before another scaling activity can start."
  default = null
}

variable "metrics_granularity" {
  description = "(Optional) The granularity to associate with the metrics to collect. The only valid value is 1Minute. Default is 1Minute."
  default = null
}

variable "enabled_metrics" {
  description = "(Optional) A list of metrics to collect. The allowed values are GroupDesiredCapacity, GroupInServiceCapacity, GroupPendingCapacity, GroupMinSize, GroupMaxSize, GroupInServiceInstances, GroupPendingInstances, GroupStandbyInstances, GroupStandbyCapacity, GroupTerminatingCapacity, GroupTerminatingInstances, GroupTotalCapacity, GroupTotalInstances."
  default = null
}

variable "wait_for_capacity_timeout" {
  description = "(Default: 10m) Maximum duration that Terraform should wait for ASG instances to be healthy before timing out. (See also Waiting for Capacity below.) Setting this to 0 causes Terraform to skip all Capacity Waiting behavior."
  default = "10m"
}

variable "wait_for_elb_capacity" {
  description = "(Optional) Setting this will cause Terraform to wait for exactly this number of healthy instances from this Auto Scaling Group in all attached load balancers on both create and update operations. (Takes precedence over min_elb_capacity behavior.) (See also Waiting for Capacity below.)"
  default = null
}

variable "min_elb_capacity" {
  description = "(Optional) Setting this causes Terraform to wait for this number of instances from this autoscaling group to show up healthy in the ELB only on creation. Updates will not wait on ELB instance number changes."
  default = null
}

variable "protect_from_scale_in" {
  description = "(Optional) Allows setting instance protection. The autoscaling group will not select instances with this setting for terminination during scale in events."
  default = null
}

variable "service_linked_role_arn" {
  description = "(Optional) The ARN of the service-linked role that the ASG will use to call other AWS services"
  default = null
}

variable "max_instance_lifetime" {
  description = "(Optional) The maximum amount of time, in seconds, that an instance can be in service, values must be either equal to 0 or between 604800 and 31536000 seconds."
  default = 0
}

variable "vpc_zone_identifier" {
  description = "(Optional) A list of subnet IDs to launch resources in."
  default = []
}

variable "launch_template" {
  description = "(Required) Nested argument containing launch template settings along with the overrides to specify multiple instance types and weights. Defined below."
  default = null
}

# Variables used in mixed_instances_policy block
# -----------------------------------------------

variable "use_mixed_instances_policy" {
  default = false
}

variable "mixed_instances_policy" {
  default = null
}

variable "launch_template_id" {
  description = "(Optional) ID of the launch template. Conflicts with launch_template_name."
  default = null
}

variable "launch_template_name" {
  description = "(Optional) Name of the launch template. Conflicts with launch_template_id."
  default = null
}

variable "template_version" {
  description = "(Optional) Template version. Can be version number, $Latest, or $Default. (Default: $Default)."
  default = null
}
# -----------------------------------------------

variable "use_instance_refresh" {
  default = false
}

variable "instance_refresh" {
  default = null
}